global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'collab-backend'
    static_configs:
      - targets: ['app:3000']  
    metrics_path: /metrics
    scheme: http